### PR TITLE
Auto ignore files and folders in .gitignore

### LINKED ISSUE #2: Auto ignore files and folders in .gitignore
Hello! Thanks for this.

This is a small feature request, I was running alder in a project that contains a `node_modules` folder and it takes a while, plus it has a lot file I was not interested in listing. I thought it would be nice if by default it would pick up the `.gitignore` file and skip those folders entirely. This would make scanning code project folders a breeze 🌬

If you think this make sense I can try to PR it.

### PR DESCRIPTION
**Pull request by xaviervia**
Fixes #2

I would like to add an option to _not_ ignore things in `.gitignore`. I was thinking that maybe it could be done when the `-a` flag is passed, but maybe there should be a dedicated flag as well. I couldn’t come up with a name for it though.

Another thing: I noticed that the structure of the code is hard to test, but I guessed that this is a tradeoff to get good speed (alder is surprisingly fast for a Node.js tool). Is that so? I thought about putting the extra functionality somewhere else to make it easier to test.

### CODE REVIEW

**Comment by aweary** [comment]
Thanks for the PR @xaviervia! After thinking about this more, I'm worried about having this be the default behavior. Having to iterate through each ignore pattern for every node in the directory tree seems like it will be a big performance hit. I think it might be a good idea to place this behind a flag.

**Comment by oieduardorabelo** [comment]
I would agree to put it behind a flag,

As a user, I always use Alder with a target directory and `--depth=1`,

e.g.

```sh
alias tree="alder --depth=1"
```

and when I need to list everything, I use `alder <path-to-folder>` (and sometimes the `--exclude` pattern)

**Comment by xaviervia** [comment]
Sure thing. Personally I do the opposite, since files in `.gitignore` include `node_modules`. Listing those makes the output less useful, and in some terminals it just crashes them :D

I'll update the branch and add the flag.

**Comment by xaviervia** [comment]
I added the `-I` flag to ignore entries in `.gitignore`. It will not do it by default now.

I’m having some slight issues with the tests (neat job with those BTW). I am trying to figure out a way to handle them but maybe you have better ideas:

1. The test for the `-D` flag is rather fragile:

screen shot 2017-02-03 at 10 57 28

The reason is that it’s fairly easy for the directory modification date to get accidentally modified, and rolling back to the correct one requires some git wizardry. 

2. Testing the `-I` flag with fixtures means that there should be some `.gitignore` files in the `fixtures` structure and that there should be some files that match the rules in those `.gitignore` files. Well, this also means that git will ignore them, so they won’t get included in the repository when pushing.

My guess is that the test scenario should also create and destroy the `.gitignore` files, so that it’s not necessary to push them. This is a bigger change to the testing suite, and of course will create more problems for the `-D` test.

**Comment by aweary** [comment]
Thanks @xaviervia. The current test suite is definitely not stable and will need more work to be useful. For now we can probably just remove the tests for flags that don't produce consistent results across machines (like date modified) and figure out a different way to test those.

FWIW you can update your local snapshot by running the tests with the `-u` flag.

**Comment by xaviervia** [comment]
Hi! Just a quick update: the failing test is due to Travis having the previous snapshots available. Unfortunately I cannot see a way to clean it from my side. Other than that it should be working now :)

**Pull request merged**
